name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check-python-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run Ruff
        run: uvx ruff check --output-format=github .

  test-python-package:
    needs: check-python-package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest

      - name: Test installation
        run: uv run ms2rescore --help

  test-windows-installer:
    # Only run on push to main (e.g., after PR merge)
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
          enable-cache: true

      - name: Install package and dependencies
        run: uv sync --group installer

      - name: Install Inno Setup
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install innosetup -y --allow-unofficial

      - name: Run pyinstaller
        run: uv run pyinstaller ./ms2rescore.spec --clean --noconfirm

      - name: Test built exe
        run: dist/ms2rescore/ms2rescore.exe

      - name: Run Inno Setup
        run: ISCC.exe ./ms2rescore_innosetup.iss /DAppVersion=test-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*.exe
